= Интернационализация и локализация

== Общие принципы
* Интернационализация осуществлена при помощи подключения плагина https://vue-i18n.intlify.dev/[vue3-i18n]
* Для настройки новой локали создаётся json файл с определённой структурой со следующими правилами:
** Вложенная структруа должна иметь четыре уровня
** Верхний уровень определяет название экранной формы
** Второй уровень - тип элемента управления (кнопки, поля таблицы, поля карточки и т.п.)
** Третий уровень - название элемента управления
** Нижний уроваень - вид константы для элемента управления (заголовок, всплывающая подсказка)

== Подключение плагина интернационализации
[source, json, indent=0]
.package.json
----
include::../../package.json[tag=version_i18n]
----
[source, json, indent=0]
----
include::../../package.json[tag=version_dev_i18n]
----
[source, js, indent=0]
.vite.config.ts
----
include::../../vite.config.ts[tag=vuei18n]
----
.Подключение плагина
[source, js, indent=0]
----
include::../../src/plugins/i18n.ts[]
----

== Примеры использования интернационализации
[source,xml, indent=0]
.Интернационализация в шаблоне (например, заголовки, футеры)
----
include::../../src/components/UrlStatePage.vue[tag=template_i18n]
----
[source,js, indent=0]
.Интернационализация в компоненте
----
include::../../src/components/GridPage.vue[tag=import_vuei18n]
----
[source,js, indent=0]
----
include::../../src/components/GridPage.vue[tag=vuei18n]
----
[source,js, indent=0]
.Интернационализация в произвольном месте кода (например, содержимое грида)
----
include::../../src/components/GridPage.vue[tag=import_plugins_vuei18n]
----
[source,js, indent=0]
----
include::../../src/components/GridPage.vue[tag=plugins_vuei18n]
----
